# Generated by Django 4.0.5 on 2022-06-30 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_photo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='username',
            field=models.ForeignKey(max_length=16, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
